### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by lmj282371** [harshitt13/Stock-Market-Prediction-Model#1]
I followed the steps one by one, using Python version 3.9, but encountered an error when running src/fetch_data.py. The error message is as follows:
File "D:\anaconda3\envs\gupiao\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'

**Comment by harshitt13** [comment]
Hey,
Thanks for your patience. I have updated the code. I hope your issues have been resolved.

Harshit Kushwaha
